name: Medical_Expenses

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permission:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - users: actions/checkout@v3
      - name: Set Up Python 3.12.4
        uses: actions/checkout@v3
        with:
          python-version: "3.12.4"